config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :searches

  get 'games/most_played', to: 'games#most_played', as: :most_played
  resources :games do
    resources :reviews
  end
  resources :users, only: [:show]
  # root 'games#index'
  root 'games#welcome'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :game_platforms
    has_many :platforms, through: :game_platforms
    has_many :game_genres
    has_many :genres, through: :game_genres
    has_many :reviews
    has_many :users, through: :reviews
    
    def self.search(search)
        if search
            Game.where("title LIKE ?", "%#{search}%")
        else
            Game.all
        end
    end

    def self.most_played
        all.max_by(3){|game| game.reviews.count}
    end

    def self.top_rated
        all_with_reviews.max_by(10){|game| game.reviews.average(:rating)}
    end

    def self.all_with_reviews
        all.select{|game| game.reviews.length > 0}
    end
end

app/models/game_genre.rb
class GameGenre < ApplicationRecord
    belongs_to :game
    belongs_to :genre
end

app/models/game_platform.rb
class GamePlatform < ApplicationRecord
    belongs_to :game
    belongs_to :platform
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :game_genre
    has_many :games, through: :game_genre

    def self.unique_genres
        Genre.all.uniq{|genre| genre.name}
    end
end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :game_platforms
    has_many :games, through: :game_platforms

    # def self.unique_platforms
    #     Platform.all.uniq{|platform| platform.platforms}
    # end

    def platform_name
        Platform.all.each do |platform| 
            
            platform.name
            
          end
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :game
    belongs_to :user
    validates_inclusion_of :rating, :in => 1..5
end

app/models/search.rb
class Search < ApplicationRecord
   
    def games
        @games ||= find_games
    end

private 

    def find_games
        games = Game.order(:name)
        games = games.where("title LIKE ?", "%#{keyword}%") if keyword.present?
        games = games.where(genre_id: genre_id) if genre_id.present?
        games = games.where(platform_id: platform_id) if platform_id.present?
        return games
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :games, through: :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
before_action :find_game, only: [:show]

    def welcome
    end
    
    def index
        if params[:genre].blank? && params[:platform].blank?
            @games = Game.all
            @games = Game.search(params[:search])
        elsif params[:platform].blank?
            @games = Genre.find_by(name: params[:genre]).games
        elsif params[:genre].blank? 
            @games = Platform.find_by(name: params[:platform]).games
        end  
    end

    def most_played
    end

    def show
        if @game.reviews.blank?
            @average_review = "No Reviews have been added to this game"
        else
            @average_review = @game.reviews.average(:rating).round(2)
        end
    end

    private

    def game_params
        params.require(:game).permit(:title, :genre_id)
    end

    def find_game
        @game = Game.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_game
    before_action :find_review, only: [:edit, :update, :destroy]

    def new
        @review = Review.new
        if current_user 
            @review = Review.where(user_id: current_user.id, game_id: params[:game_id]).first_or_initialize 
            if @review.id.present? 
              render 'edit' 
            end 
        end 
        
    end

    def show
    end


    def create
        @review = Review.new(review_params)
        @review.game_id = @game.id
        @review.user_id = current_user.id
        if @review.save
            redirect_to game_path(@game)
        else
            render :new
        end
    end

    def edit
        
    end

    def update
        if @review.update(review_params)
            redirect_to game_path(@game)
        else
            render :edit
        end
    end

    def destroy
        @review.destroy
        redirect_to game_path(@game)
    end
        
    

    private

    def review_params
        params.require(:review).permit(:rating, :content)
    end

    def find_game
        @game = Game.find(params[:game_id])
    end

    def find_review
        @review = Review.find(params[:id])
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    
        def new
            @search = Search.new
            # @platforms = Game.all.uniq.pluck(:platform)
        end
    
        def create
            @search = Search.create(search_params)
            redirect_to @search
        end
    
        def show
            
            @search = Search.find(params[:id])
        end
    
        private
    
        def search_params
            params.require(:search).permit(:keywords, :genre_id, :platform_id)
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/edit.html.erb
<h1>Edit Game</h1>

<%= form_for @game, :html => {:multipart => true} do |f| %>
  <%=f.collection_select :category_id, Category.all, :id, :genre, :prompt => "Select a category" %> <br> <br>
  <%= f.label :name %>
  <%= f.text_field :title%> <br> <br>

  <%= f.label :image%>
  <%= f.file_field :game_image%><br> <br>

  <%= f.label :description %>
  <%= f.text_area :description%><br><br>

  <%= f.label :publisher %>
  <%= f.text_field :publisher%> <br> <br>

  <%= f.button "Edit Game"%>
<% end %>

app/views/games/index.html.erb
<h1 id="games_header">List of Games</h1>
<h3><%=params[:genre]%></h3>

<%= form_tag games_path, :method => 'get' do %>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
<% end %>
<br>
<%= button_to 'Most Played and Top Rated Games', most_played_path, method: :get %><br>

<% if @games.count == 0%>
    <h4>There are no games in this category</h4>
<% else %>
    <% @games.each do |game| %>
    <div id="game_list"><span><%= link_to game.title, game_path(game) %></span></div>
    <% end %>
    <br>
<% end %>

app/views/games/most_played.html.erb
<br>
<h1 id = "game_details">Top 3 Most Played Games</h1>
<br>
<% Game.most_played.each do |game| %>
<br>
<h2 id = "game_details"><%= link_to "#{game.title}", game_path(game) %></h2>
<br>
<% end %>

<br>
<br>
<h1 id = "game_details">Top 10 Highest Rated Games</h1>
<br>
<% Game.top_rated.each do |game| %>
<br>
<h2 id = "game_details"><%= link_to "#{game.title}", game_path(game) %></h2>
<br>
<% end %>
<div id="some_space">
</div>

app/views/games/new.html.erb
<h1> New Game </h1>

<%= form_for @game do |f| %>
  <%=f.collection_select :category_id, Category.all, :id, :genre, :prompt => "Select a category" %> <br> <br>
  <%= f.label :name %>
  <%= f.text_field :title%> <br> <br>

  <%= f.label :image%>
  <%= f.file_field :game_image%>

  <%= f.label :description %>
  <%= f.text_area :description%><br><br>

  <%= f.label :publisher %>
  <%= f.text_field :publisher%> <br> <br>

  

  <%= f.button "Create Game"%>
<% end %>

app/views/games/show.html.erb
<h1 id = "game_details"><%= @game.title%></h1>
<br>
<img id="unavail" src='../assets/jf_letters_unavail.png'>
<br>
    <%if user_signed_in? %>
    <br>
        <%= button_to "Click here to write a review for #{@game.title}", new_game_review_path(@game), method: :get %>
        <%if Review.find_by(user_id: current_user.id) %>    
        <%end%>
    <%end%>

<h3 id="game_details">Average Rating:  </h3>
<h4 id = "game_details"> <%= @average_review %></h4>

<div>
    <% @game.genres.each do |genre| %>
    <h2 id= "game_details"><%="| #{genre.name} |"%> </h2>
    <% end %>
</div>

<div>
    <h2 id = "game_details">Available on the following platform(s):</h2>
    <br>
    <% @game.platforms.each do |platform| %>
    <h2 id= "game_details"> <%= "| #{platform.name} |" %> </h2>
    <% end %>
</div>
<br>
<div class ="row">

    <div id= "review_show_box">
    <h2 id ="game_details"><%= render @game.reviews %></h2>

    <%if user_signed_in? %>
            <% if @game.reviews.count == 0 %>
            <br>
            <br>
            <h3 id="game_details">Be the first the review this game!</h3>
            <br>
            <% end %>
            <br>
        <%if Review.find_by(user_id: current_user.id) %>    
        <%end%>
    <%end%>

    </div>
    <div id = "some_space">
    </div>
</div>

app/views/games/welcome.html.erb
<div id="header">
<h1 id="game_details">Welcome to JunkFood</h1>
</div>

<h1 id="game_details">What's your JunkFood???</h1>
<br>
<h2 id="game_details">What is 'JunkFood'?</h2>
<h2 id="game_details">You know when you love something, some might say, an unhealthy amount?</h2>
<h2 id="game_details">That thing, IS your JunkFood</h2>
<h2 id="game_details">For the founders here at JunkFood, </h2>
<h2 id="game_details">games are arguably our biggest JunkFood.</h2>
<h2 id="game_details">So this is where we will start, with gaming and someday, </h2>
<h2 id="game_details">you will see options for everyone's "JunkFood"</h2>
<%= button_to "Enter Here", games_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JunkFood - Gaming</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id = "box">
      <nav>
        <div class = "container">

          
          <ul class = "nav navbar-nav">
            <li id = "nav_button"><%= link_to 'All Games', games_path %> </li>
            
            
            <% if user_signed_in? %>
            <li id = "nav_button">  <%= link_to current_user.email , user_path(current_user) %>  </li>
            <li id = "nav_button"> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> </li>
            
            <%else%>
            <li id = "nav_button"> <%= link_to 'Log In', new_user_session_path %> </li>
            <li id = "nav_button"> <%= link_to 'Sign Up', new_user_registration_path %> </li>
            <% end %>
          
          </ul>

        <a href= "/" ><img id = "image_logo" src="../assets/junkfood_logo_update.png"></a>

        <ul id= "dropdown_button" class = "nav navbar-nav navbar-right">
          <li id = "nav_button" class = "dropdown"> <a href = "#" class = "dropdown-toggle" data-toggle = "dropdown" role = "button" aria-expanded = "false"> Genres <span class = "caret"> </span></a> 
            <ul class = "dropdown-menu" role ="menu "> 
              <% Genre.unique_genres.each do |genre| %>
                <li>
                  <%= link_to genre.name, games_path(genre: genre.name) %>
                </li>
              <%end%>
            </ul>
          </li>
        </ul>

        <ul class = "nav navbar-nav navbar-right">
          <li id = "nav_button" class = "dropdown"> <a href = "#" class = "dropdown-toggle" data-toggle = "dropdown" role = "button" aria-expanded = "false"> Platforms <span class = "caret"> </span></a> 
            <ul class = "dropdown-menu" role ="menu "> 
              <% Platform.all.each do |platform| %>
                <li>
                  <%= link_to platform.name, games_path(platform: platform.name) %>
                </li>
              <%end%>
            </ul>
          </li>
        </ul>
      </nav>
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
      <footer id= "footer">
        <% unless user_signed_in? %>
                <h3 id="footer_link_text"><%= link_to "Sign Up", new_user_registration_path%> / <%= link_to "Log In", new_user_session_path%> to write a review!</h3>
        <% end %>
      </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@game, @game.reviews.build]) do |f| %>
    <% f.label :rating, size: 5 %> Rating:  <br>
    <%= f.number_field :rating, size: 5%> <br> <br>

    <% f.label :content %> Review: <br>
    <%= f.text_area :content%> 

    <% f.button "Submit" %>
<% end %>






  

 

app/views/reviews/_review.html.erb
<p id= "review rating"> <%= review.rating %> / 5</p>
<br>
<p id= "review"> <%= review.content %></p>
<br>
<p id= "review"><i> <%= review.user.email%></i></p>
<div class= "edit-delete-user">
<%if user_signed_in? %>
    <%if review.user_id == current_user.id %> <br>
            <h3><%= button_to 'Edit Review', edit_game_review_path(review.game, review), method: :get %></h3>
            <h3><%= button_to 'Delete Review', game_review_path(review.game, review), method: :delete, data: { confirm: "Are you sure?"} %></h3>      
    <%end%>
</div><br>
    
<%end%>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_for([@game, @review]) do |f|%>

    <% f.label :rating%> Rating:  <br>
    <%= f.number_field :rating, in: 1..5%> <br> <br>

    <% f.label :content %> Review: <br>
    <%= f.text_area :content%> <br> <br>

    <%= f.submit "Submit" %>

<% end %>

app/views/reviews/index.html.erb
<h1 id="review_header">Here is a list of all our game reviews:</h1>

<% @reviews.each do |review| %>
<div>
<h2><%= review.game %></h2>
<p><%= review.content %></p>
<h3><%= "#{review.rating}/10" %></h3>
</div>
<% end %>

<div id="button">
    <%= button_to "Home", welcome_path, method: :get %>
</div>

<div id="button">
    <%= button_to "Write a new review", new_review_path, method: :get %>
</div>

<div id="button">
    <%= button_to "Check out Games", games_path, method: :get %>
</div>

app/views/reviews/new.html.erb
<h1> New Review </h1>

<%= form_for([@game, @game.reviews.build]) do |f| %>
   <% f.label :rating%> Rating:  <br>
    <%= f.number_field :rating, in: 1..5%> <br> <br>

    <% f.label :content %> Review: <br>
    <%= f.text_area :content%> <br> <br>

    <%= f.submit "Submit" %>
<% end %>

app/views/searches/new.html.erb
<h1> Custom Search </h1>
<%= form_for @search do |f| %>

    <%= f.label :keyword %>:
    <%= f.text_field :keyword %>

    <%#= f.label :genre_id %>:
    <%#= f.text_field :genre_id %>

    
    <%# <%= f.label :platform_id %> %>
    <%# <%= f.collection_select :platform_id, Platform.order(:name),:id, :name, :include_blank => true%> %>

   

    <%= f.submit "Search"%>

<% end %>




<%= link_to 'Back', games_path %>

app/views/searches/show.html.erb
<h2> Search Results </h2>

<p> <%= link_to 'Back', new_search_path %> </p>

<% if @search

    
    <h1> <%= @search.games[2].title %> </h1>
 
    



    
<%end%>

   

app/views/users/show.html.erb
<br>
<h1><u><%= current_user.email %>'s Profile Page</u></h1>
    <% current_user.reviews.each do |review| %>
<h2 id = "game_details"><%= link_to "#{review.game.title}", game_path(review.game)  %> || </h2>
    <% review.game.platforms. each do |platform| %>
<h2 id = "game_details"><%= platform.name %> || </h2>
<% end %>
<%= button_to "Edit your review for #{review.game.title}", new_game_review_path(review.game), method: :get %>
<%= button_to "Delete your review for #{review.game.title}", game_review_path(review.game, review), method: :delete, data: { confirm: "Are you sure?"} %>
<h2 id = "review">Your rating: <%= review.rating  %> / 5</h2>
    <br>
<h2 id = "review"><%= review.content  %></h2>
    <br>
    <br>
    <br>
<% end %>
<h4 id ="request_delete_account">If you would like to delete your account, please send a request to TeamJunkFood@JunkFood.com</h4>